# This code is part of Qiskit.
#
# (C) Copyright IBM 2018, 2020.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

notifications:
  email: false

cache:
  pip: true
  directories:
    - .stestr
os: linux
dist: xenial

language: python
python: 3.7

git:
  depth: false

env:
  global:
    - DEPENDENCY_BRANCH=$(if [[ "$TRAVIS_BRANCH" == stable* ]]; then echo "stable"; else echo "master"; fi)
    - INIT_FILE="$TRAVIS_BUILD_DIR/qiskit/__init__.py"

stage_dependencies: &stage_dependencies
  before_install:
    - |
      if [ -f $INIT_FILE ]; then
        # stops travis if __init__.py exists under qiskit
        echo "File '$INIT_FILE' found. It should not exist, since this repo extends qiskit namespace.";
        travis_terminate 1;
      fi
    - |
      if [ "$INSTALL_PSI4" == "yes" ]; then
        # Download and install miniconda psi4
        wget http://vergil.chemistry.gatech.edu/psicode-download/Psi4conda-1.3.2-py37-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda activate
      fi
    - pip install -U 'pip<20.0.0'
    - pip install -U setuptools wheel
    - |
      if [ "$DEPENDENCY_BRANCH" == "master" ]; then
        pip install cython
        # Installing qiskit-terra master branch...
        pip install https://github.com/Qiskit/qiskit-terra/archive/master.zip --progress-bar off
        # Installing qiskit-ignis master branch...
        pip install https://github.com/Qiskit/qiskit-ignis/archive/master.zip --progress-bar off
        # Installing qiskit-ibmq-provider master branch...
        pip install https://github.com/Qiskit/qiskit-ibmq-provider/archive/master.zip --progress-bar off
        # install qiskit-aer build dependencies
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt-get -y install g++-7
        sudo apt-get -y install libopenblas-dev
        # Clone qiskit-aer
        git clone --recurse-submodules https://github.com/Qiskit/qiskit-aer.git /tmp/qiskit-aer
        cd /tmp/qiskit-aer
        # Install qiskit-aer requirements.
        pip install -U -c constraints.txt -r requirements-dev.txt --progress-bar off
        # Build qiskit-aer with Thrust OpenMP CPU backend
        python setup.py bdist_wheel -- -DCMAKE_CXX_COMPILER=g++-7 -DAER_THRUST_BACKEND=OMP -- -j4
        pip install dist/qiskit_aer*whl
        # back to current repo directory
        cd $TRAVIS_BUILD_DIR
      fi
    # install Aqua and Aqua dev. requirements
    - pip install -e $TRAVIS_BUILD_DIR --progress-bar off
    - pip install -U -c constraints.txt -r requirements-dev.txt --progress-bar off
    - |
      if [ "$DEPENDENCY_BRANCH" != "master" ]; then
        pip install qiskit-ibmq-provider
      fi

stage_test_aqua: &stage_test_aqua
  <<: *stage_dependencies
  install:
    - |
      cat > selection.txt <<EOF
      test.aqua.operators.test_tpb_grouped_weigted_pauli_operator
      test.aqua.operators.test_weighted_pauli_operator
      test.aqua.test_custom_circuit_oracle
      test.aqua.test_entangler_map
      test.aqua.test_eoh
      test.aqua.test_exact_eigen_solver
      test.aqua.test_exact_ls_solver
      test.aqua.test_fixed_value_comparator
      test.aqua.test_hhl
      test.aqua.test_initial_state_custom
      test.aqua.test_initial_state_zero
      test.aqua.test_input_parser
      test.aqua.test_iqpe
      test.aqua.test_logical_expression_oracle
      test.aqua.test_lookup_rotation
      test.aqua.test_mct
      test.aqua.test_mcu1
      test.aqua.test_measure_error_mitigation
      test.aqua.test_nlopt_optimizers
      test.aqua.test_optimizers
      test.aqua.test_qgan
      test.aqua.test_qpe
      test.aqua.test_qsvm
      test.aqua.test_rmg
      test.aqua.test_ry
      test.aqua.test_shor
      test.aqua.test_simon
      EOF

jobs:
  include:
    - stage: Checks and Tests
      <<: *stage_dependencies
      name: "Spell, Style, Lint, Docs check"
      if: tag IS blank
      install:
        # install spell check libraries
        - sudo apt-get -y install python3-enchant
        - sudo apt-get -y install hunspell-en-us
        - pip install pyenchant
      script: make -k all_check SPHINXOPTS=-W
    - name: "Test Aqua 1 Python 3.7"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua1
          paths: aqua1.dat
      before_script:
        - pip install cvxopt
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/aqua run --blacklist-file selection.txt && coverage3 combine && mv .coverage aqua1.dat
    - name: "Test Aqua 1 Python 3.8"
      <<: *stage_test_aqua
      if: tag IS blank
      python: 3.8
      before_script:
        - pip install cvxopt
      script: stestr --test-path test/aqua run --blacklist-file selection.txt
    - name: "Test Aqua 2 Python 3.7"
      <<: *stage_test_aqua
      if: tag IS blank
      workspaces:
        create:
          name: aqua2
          paths: aqua2.dat
      before_script:
        - pip install cvxopt
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/aqua run --whitelist-file selection.txt && coverage3 combine && mv .coverage aqua2.dat
    - name: "Test Aqua 2 Python 3.8"
      <<: *stage_test_aqua
      if: tag IS blank
      python: 3.8
      before_script:
        - pip install cvxopt
      script: stestr --test-path test/aqua run --whitelist-file selection.txt
    - name: "Test Chemistry Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      env:
        - INSTALL_PSI4=yes
        - OPENBLAS_NUM_THREADS=1
      workspaces:
        create:
          name: chemistry
          paths: chemistry.dat
      install:
        # install gaussian dependency libgfortran 5
        - sudo apt-get -y update
        - sudo apt-get -y install libgfortran5
        # Installing pyquante2 master branch...
        - pip install https://github.com/rpmuller/pyquante2/archive/master.zip --progress-bar off
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/chemistry run && coverage3 combine && mv .coverage chemistry.dat
    - name: "Test Chemistry Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      python: 3.8
      env: OPENBLAS_NUM_THREADS=1
      install:
        # install gaussian dependency libgfortran 5
        - sudo apt-get -y update
        - sudo apt-get -y install libgfortran5
        # Installing pyquante2 master branch...
        - pip install https://github.com/rpmuller/pyquante2/archive/master.zip --progress-bar off
      script: stestr --test-path test/chemistry run
    - name: "Test Finance Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: finance
          paths: finance.dat
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/finance run && coverage3 combine && mv .coverage finance.dat
    - name: "Test Finance Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      python: 3.8
      script: stestr --test-path test/finance run
    - name: "Test Machine Learning Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: ml
          paths: ml.dat
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/ml run && coverage3 combine && mv .coverage ml.dat
    - name: "Test Machine Learning Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      python: 3.8
      script: stestr --test-path test/ml run
    - name: "Test Optimization Python 3.7"
      <<: *stage_dependencies
      if: tag IS blank
      workspaces:
        create:
          name: optimization
          paths: optimization.dat
      before_script:
        - export PYTHON="coverage3 run --source qiskit/aqua,qiskit/chemistry,qiskit/finance,qiskit/ml,qiskit/optimization --omit */gauopen/* --parallel-mode"
      script: stestr --test-path test/optimization run && coverage3 combine && mv .coverage optimization.dat
    - name: "Test Optimization Python 3.8"
      <<: *stage_dependencies
      if: tag IS blank
      python: 3.8
      script: stestr --test-path test/optimization run
    - stage: Coverage
      name: "Combine all coverages and upload to Coveralls"
      if: tag IS blank
      workspaces:
        use:
          - aqua1
          - aqua2
          - chemistry
          - finance
          - ml
          - optimization
      install:
        - pip install -U coverage coveralls diff-cover
      script:
        - coverage3 combine aqua1.dat aqua2.dat chemistry.dat finance.dat ml.dat optimization.dat
        - coveralls || true
        - coverage3 xml
        - diff-cover --compare-branch master coverage.xml || true
    - stage: Deploy
      name: "Deploy to Pypi"
      if: tag IS present
      python: 3.7
      env:
        - TWINE_USERNAME=qiskit
      install:
        - pip install -U twine pip setuptools virtualenv wheel
      script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/qiskit*
